<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */


/* `dbname`.`countries` */
$countries = array(
  array('id' => '1','country_name' => 'Afghanistan','nationality' => 'Afghan','dial_code' => '+93','iso_alpha_2' => 'AF','iso_alpha_3' => 'AFG'),
  array('id' => '2','country_name' => 'Aland Islands','nationality' => 'Aland Islands','dial_code' => '+358','iso_alpha_2' => 'AX','iso_alpha_3' => 'ALA'),
  array('id' => '3','country_name' => 'Albania','nationality' => 'Albanian','dial_code' => '+355','iso_alpha_2' => 'AL','iso_alpha_3' => 'ALB'),
  array('id' => '4','country_name' => 'Algeria','nationality' => 'Algerian','dial_code' => '+213','iso_alpha_2' => 'DZ','iso_alpha_3' => 'DZA'),
  array('id' => '5','country_name' => 'American Samoa','nationality' => 'American Saoma','dial_code' => '+1','iso_alpha_2' => 'AS','iso_alpha_3' => 'ASM'),
  array('id' => '6','country_name' => 'Andorra','nationality' => 'Andorran','dial_code' => '+376','iso_alpha_2' => 'AD','iso_alpha_3' => 'AND'),
  array('id' => '7','country_name' => 'Angola','nationality' => 'Angolan','dial_code' => '+244','iso_alpha_2' => 'AO','iso_alpha_3' => 'AGO'),
  array('id' => '8','country_name' => 'Anguilla','nationality' => 'Anguillan','dial_code' => '+1','iso_alpha_2' => 'AI','iso_alpha_3' => 'AIA'),
  array('id' => '9','country_name' => 'Antarctica','nationality' => 'Antarctican','dial_code' => '+672','iso_alpha_2' => 'AQ','iso_alpha_3' => 'ATA'),
  array('id' => '10','country_name' => 'Antigua And Barbuda','nationality' => 'Antiguans','dial_code' => '+1','iso_alpha_2' => 'AG','iso_alpha_3' => 'ATG'),
  array('id' => '11','country_name' => 'Argentina','nationality' => 'Argentinean','dial_code' => '+54','iso_alpha_2' => 'AR','iso_alpha_3' => 'ARG'),
  array('id' => '12','country_name' => 'Armenia','nationality' => 'Armenian','dial_code' => '+374','iso_alpha_2' => 'AM','iso_alpha_3' => 'ARM'),
  array('id' => '13','country_name' => 'Aruba','nationality' => 'Aruba','dial_code' => '+297','iso_alpha_2' => 'AW','iso_alpha_3' => 'ABW'),
  array('id' => '14','country_name' => 'Australia','nationality' => 'Australian','dial_code' => '+61','iso_alpha_2' => 'AU','iso_alpha_3' => 'AUS'),
  array('id' => '15','country_name' => 'Austria','nationality' => 'Austrian','dial_code' => '+43','iso_alpha_2' => 'AT','iso_alpha_3' => 'AUT'),
  array('id' => '16','country_name' => 'Azerbaijan','nationality' => 'Azerbaijani','dial_code' => '+994','iso_alpha_2' => 'AZ','iso_alpha_3' => 'AZE'),
  array('id' => '17','country_name' => 'Bahamas','nationality' => 'Bahamian','dial_code' => '+1','iso_alpha_2' => 'BS','iso_alpha_3' => 'BHS'),
  array('id' => '18','country_name' => 'Bahrain','nationality' => 'Bahraini','dial_code' => '+973','iso_alpha_2' => 'BH','iso_alpha_3' => 'BHR'),
  array('id' => '19','country_name' => 'Bangladesh','nationality' => 'Bangladeshi','dial_code' => '+880','iso_alpha_2' => 'BD','iso_alpha_3' => 'BGD'),
  array('id' => '20','country_name' => 'Barbados','nationality' => 'Barbudans','dial_code' => '+1','iso_alpha_2' => 'BB','iso_alpha_3' => 'BRB'),
  array('id' => '21','country_name' => 'Belarus','nationality' => 'Belarusian','dial_code' => '+375','iso_alpha_2' => 'BY','iso_alpha_3' => 'BLR'),
  array('id' => '22','country_name' => 'Belgium','nationality' => 'Belgian','dial_code' => '+32','iso_alpha_2' => 'BE','iso_alpha_3' => 'BEL'),
  array('id' => '23','country_name' => 'Belize','nationality' => 'Belizean','dial_code' => '+501','iso_alpha_2' => 'BZ','iso_alpha_3' => 'BLZ'),
  array('id' => '24','country_name' => 'Benin','nationality' => 'Beninese','dial_code' => '+229','iso_alpha_2' => 'BJ','iso_alpha_3' => 'BEN'),
  array('id' => '25','country_name' => 'Bermuda','nationality' => 'Bermudan','dial_code' => '+1','iso_alpha_2' => 'BM','iso_alpha_3' => 'BMU'),
  array('id' => '26','country_name' => 'Bhutan','nationality' => 'Bhutanese','dial_code' => '+975','iso_alpha_2' => 'BT','iso_alpha_3' => 'BTN'),
  array('id' => '27','country_name' => 'Bolivia','nationality' => 'Bolivian','dial_code' => '+591','iso_alpha_2' => 'BO','iso_alpha_3' => 'BOL'),
  array('id' => '28','country_name' => 'Bosnia And Herzegovina','nationality' => 'Bosnian','dial_code' => '+387','iso_alpha_2' => 'BA','iso_alpha_3' => 'BIH'),
  array('id' => '29','country_name' => 'Botswana','nationality' => 'Botswananian','dial_code' => '+267','iso_alpha_2' => 'BW','iso_alpha_3' => 'BWA'),
  array('id' => '30','country_name' => 'Bouvet Island','nationality' => 'Bouvet Island','dial_code' => '+47','iso_alpha_2' => 'BV','iso_alpha_3' => 'BVT'),
  array('id' => '31','country_name' => 'Brazil','nationality' => 'Brazilian','dial_code' => '+55','iso_alpha_2' => 'BR','iso_alpha_3' => 'BRA'),
  array('id' => '32','country_name' => 'British Indian Ocean Territory','nationality' => 'British Indian Ocean Territory','dial_code' => '+246','iso_alpha_2' => 'IO','iso_alpha_3' => 'IOT'),
  array('id' => '33','country_name' => 'Virgin Islands, British','nationality' => 'Virgin Islands, British','dial_code' => '+1','iso_alpha_2' => 'VG','iso_alpha_3' => 'VGB'),
  array('id' => '34','country_name' => 'Brunei Darussalam','nationality' => 'Bruneian','dial_code' => '+673','iso_alpha_2' => 'BN','iso_alpha_3' => 'BRN'),
  array('id' => '35','country_name' => 'Bulgaria','nationality' => 'Bulgarian','dial_code' => '+359','iso_alpha_2' => 'BG','iso_alpha_3' => 'BGR'),
  array('id' => '36','country_name' => 'Burkina Faso','nationality' => 'Burkinabe','dial_code' => '+226','iso_alpha_2' => 'BF','iso_alpha_3' => 'BFA'),
  array('id' => '37','country_name' => 'Burundi','nationality' => 'Burundian','dial_code' => '+257','iso_alpha_2' => 'BI','iso_alpha_3' => 'BDI'),
  array('id' => '38','country_name' => 'Cambodia','nationality' => 'Cambodian','dial_code' => '+855','iso_alpha_2' => 'KH','iso_alpha_3' => 'KHM'),
  array('id' => '39','country_name' => 'Cameroon','nationality' => 'Cameroonian','dial_code' => '+237','iso_alpha_2' => 'CM','iso_alpha_3' => 'CMR'),
  array('id' => '40','country_name' => 'Canada','nationality' => 'Canadian','dial_code' => '+1','iso_alpha_2' => 'CA','iso_alpha_3' => 'CAN'),
  array('id' => '41','country_name' => 'Cape Verde','nationality' => 'Cape Verdean','dial_code' => '+238','iso_alpha_2' => 'CV','iso_alpha_3' => 'CPV'),
  array('id' => '42','country_name' => 'Cayman Islands','nationality' => 'Cayman Islands','dial_code' => '+1','iso_alpha_2' => 'KY','iso_alpha_3' => 'CYM'),
  array('id' => '43','country_name' => 'Central African Republic','nationality' => 'Central African','dial_code' => '+236','iso_alpha_2' => 'CF','iso_alpha_3' => 'CAF'),
  array('id' => '44','country_name' => 'Chad','nationality' => 'Chadian','dial_code' => '+235','iso_alpha_2' => 'TD','iso_alpha_3' => 'TCD'),
  array('id' => '45','country_name' => 'Chile','nationality' => 'Chilean','dial_code' => '+56','iso_alpha_2' => 'CL','iso_alpha_3' => 'CHL'),
  array('id' => '46','country_name' => 'China','nationality' => 'Chinese','dial_code' => '+86','iso_alpha_2' => 'CN','iso_alpha_3' => 'CHN'),
  array('id' => '47','country_name' => 'Christmas Island','nationality' => 'Christmas Island','dial_code' => '+61','iso_alpha_2' => 'CX','iso_alpha_3' => 'CXR'),
  array('id' => '48','country_name' => 'Cocos (Keeling) Islands','nationality' => 'Cocos (Keeling) Islands','dial_code' => '+61','iso_alpha_2' => 'CC','iso_alpha_3' => 'CCK'),
  array('id' => '49','country_name' => 'Colombia','nationality' => 'Colombian','dial_code' => '+57','iso_alpha_2' => 'CO','iso_alpha_3' => 'COL'),
  array('id' => '50','country_name' => 'Comoros','nationality' => 'Comoran','dial_code' => '+269','iso_alpha_2' => 'KM','iso_alpha_3' => 'COM'),
  array('id' => '51','country_name' => 'Congo','nationality' => 'Congolese','dial_code' => '+242','iso_alpha_2' => 'CG','iso_alpha_3' => 'COG'),
  array('id' => '52','country_name' => 'Cook Island','nationality' => 'Cook Islander','dial_code' => '+682','iso_alpha_2' => 'CK','iso_alpha_3' => 'COK'),
  array('id' => '53','country_name' => 'Costa Rica','nationality' => 'Costa Rican','dial_code' => '+506','iso_alpha_2' => 'CR','iso_alpha_3' => 'CRI'),
  array('id' => '54','country_name' => 'Cote D\'Ivoire','nationality' => 'Cote D\'Ivoires','dial_code' => '+225','iso_alpha_2' => 'CI','iso_alpha_3' => 'CIV'),
  array('id' => '55','country_name' => 'Croatia','nationality' => 'Croatian','dial_code' => '+385','iso_alpha_2' => 'HR','iso_alpha_3' => 'HRV'),
  array('id' => '56','country_name' => 'Cuba','nationality' => 'Cuban','dial_code' => '+53','iso_alpha_2' => 'CU','iso_alpha_3' => 'CUB'),
  array('id' => '57','country_name' => 'Curacao','nationality' => '****','dial_code' => '+599','iso_alpha_2' => 'CW','iso_alpha_3' => 'CUW'),
  array('id' => '58','country_name' => 'Cyprus','nationality' => 'Cypriot','dial_code' => '+357','iso_alpha_2' => 'CY','iso_alpha_3' => 'CYP'),
  array('id' => '59','country_name' => 'Czech Republic','nationality' => 'Czech','dial_code' => '+420','iso_alpha_2' => 'CZ','iso_alpha_3' => 'CZE'),
  array('id' => '60','country_name' => 'Democratic Republic of Congo','nationality' => 'Congolese','dial_code' => '+243','iso_alpha_2' => 'CD','iso_alpha_3' => 'COD'),
  array('id' => '61','country_name' => 'Denmark','nationality' => 'Danish','dial_code' => '+45','iso_alpha_2' => 'DK','iso_alpha_3' => 'DNK'),
  array('id' => '62','country_name' => 'Djibouti','nationality' => 'Djibouti','dial_code' => '+253','iso_alpha_2' => 'DJ','iso_alpha_3' => 'DJI'),
  array('id' => '63','country_name' => 'Dominica','nationality' => 'Dominican','dial_code' => '+1','iso_alpha_2' => 'DM','iso_alpha_3' => 'DMA'),
  array('id' => '64','country_name' => 'Dominican Republic','nationality' => 'Dominican Republic','dial_code' => '+1','iso_alpha_2' => 'DO','iso_alpha_3' => 'DOM'),
  array('id' => '65','country_name' => 'Ecuador','nationality' => 'Ecuadorean','dial_code' => '+593','iso_alpha_2' => 'EC','iso_alpha_3' => 'ECU'),
  array('id' => '66','country_name' => 'Egypt','nationality' => 'Egyptian','dial_code' => '+20','iso_alpha_2' => 'EG','iso_alpha_3' => 'EGY'),
  array('id' => '67','country_name' => 'El Salvador','nationality' => 'El Salvadorian','dial_code' => '+503','iso_alpha_2' => 'SV','iso_alpha_3' => 'SLV'),
  array('id' => '68','country_name' => 'Equatorial Guinea','nationality' => 'Equatorial Guinean','dial_code' => '+240','iso_alpha_2' => 'GQ','iso_alpha_3' => 'GNQ'),
  array('id' => '69','country_name' => 'Eritrea','nationality' => 'Eritrean','dial_code' => '+291','iso_alpha_2' => 'ER','iso_alpha_3' => 'ERI'),
  array('id' => '70','country_name' => 'Estonia','nationality' => 'Estonian','dial_code' => '+372','iso_alpha_2' => 'EE','iso_alpha_3' => 'EST'),
  array('id' => '71','country_name' => 'Ethiopia','nationality' => 'Ethiopian','dial_code' => '+251','iso_alpha_2' => 'ET','iso_alpha_3' => 'ETH'),
  array('id' => '72','country_name' => 'Falkland Islands (Malvinas)','nationality' => 'Falkland Islands (Malvinas)','dial_code' => '+500','iso_alpha_2' => 'FK','iso_alpha_3' => 'FLK'),
  array('id' => '73','country_name' => 'Faroe Islands','nationality' => 'Faroe Islands','dial_code' => '+298','iso_alpha_2' => 'FO','iso_alpha_3' => 'FRO'),
  array('id' => '74','country_name' => 'Fiji','nationality' => 'Fijian','dial_code' => '+679','iso_alpha_2' => 'FJ','iso_alpha_3' => 'FJI'),
  array('id' => '75','country_name' => 'Finland','nationality' => 'Finnish','dial_code' => '+358','iso_alpha_2' => 'FI','iso_alpha_3' => 'FIN'),
  array('id' => '76','country_name' => 'France','nationality' => 'French','dial_code' => '+33','iso_alpha_2' => 'FR','iso_alpha_3' => 'FRA'),
  array('id' => '77','country_name' => 'French Guiana','nationality' => 'French Guianese','dial_code' => '+594','iso_alpha_2' => 'GF','iso_alpha_3' => 'GUF'),
  array('id' => '78','country_name' => 'French Polynesia','nationality' => 'French Polynesia','dial_code' => '+689','iso_alpha_2' => 'PF','iso_alpha_3' => 'PYF'),
  array('id' => '79','country_name' => 'Gabon','nationality' => 'Gabonese','dial_code' => '+241','iso_alpha_2' => 'GA','iso_alpha_3' => 'GAB'),
  array('id' => '80','country_name' => 'Gambia','nationality' => 'Gambian','dial_code' => '+220','iso_alpha_2' => 'GM','iso_alpha_3' => 'GMB'),
  array('id' => '81','country_name' => 'Georgia','nationality' => 'Georgian','dial_code' => '+995','iso_alpha_2' => 'GE','iso_alpha_3' => 'GEO'),
  array('id' => '82','country_name' => 'Germany','nationality' => 'German','dial_code' => '+49','iso_alpha_2' => 'DE','iso_alpha_3' => 'DEU'),
  array('id' => '83','country_name' => 'Ghana','nationality' => 'Ghanaian','dial_code' => '+233','iso_alpha_2' => 'GH','iso_alpha_3' => 'GHA'),
  array('id' => '84','country_name' => 'Gibraltar','nationality' => 'Gibraltarian','dial_code' => '+350','iso_alpha_2' => 'GI','iso_alpha_3' => 'GIB'),
  array('id' => '85','country_name' => 'Greece','nationality' => 'Greek','dial_code' => '+30','iso_alpha_2' => 'GR','iso_alpha_3' => 'GRC'),
  array('id' => '86','country_name' => 'Greenland','nationality' => 'Greenlandian','dial_code' => '+299','iso_alpha_2' => 'GL','iso_alpha_3' => 'GRL'),
  array('id' => '87','country_name' => 'Grenada','nationality' => 'Grenadian','dial_code' => '+1','iso_alpha_2' => 'GD','iso_alpha_3' => 'GRD'),
  array('id' => '88','country_name' => 'Guadeloupe','nationality' => 'Guadeloupe','dial_code' => '+590','iso_alpha_2' => 'GP','iso_alpha_3' => 'GLP'),
  array('id' => '89','country_name' => 'Guam','nationality' => 'Guamian','dial_code' => '+1','iso_alpha_2' => 'GU','iso_alpha_3' => 'GUM'),
  array('id' => '90','country_name' => 'Guatemala','nationality' => 'Guatemalan','dial_code' => '+502','iso_alpha_2' => 'GT','iso_alpha_3' => 'GTM'),
  array('id' => '91','country_name' => 'Guernsey','nationality' => 'Guerns','dial_code' => '+44','iso_alpha_2' => 'GG','iso_alpha_3' => 'GGY'),
  array('id' => '92','country_name' => 'Guinea','nationality' => 'Guinean','dial_code' => '+224','iso_alpha_2' => 'GN','iso_alpha_3' => 'GIN'),
  array('id' => '93','country_name' => 'Guinea-Bissau','nationality' => 'Bissau-Guinean','dial_code' => '+245','iso_alpha_2' => 'GW','iso_alpha_3' => 'GNB'),
  array('id' => '94','country_name' => 'Guyana','nationality' => 'Guyanese','dial_code' => '+592','iso_alpha_2' => 'GY','iso_alpha_3' => 'GUY'),
  array('id' => '95','country_name' => 'Haiti','nationality' => 'Haitian','dial_code' => '+509','iso_alpha_2' => 'HT','iso_alpha_3' => 'HTI'),
  array('id' => '96','country_name' => 'Honduras','nationality' => 'Honduran','dial_code' => '+504','iso_alpha_2' => 'HN','iso_alpha_3' => 'HND'),
  array('id' => '97','country_name' => 'Hong Kong','nationality' => 'Hong Kong (Chinese)','dial_code' => '+852','iso_alpha_2' => 'HK','iso_alpha_3' => 'HKG'),
  array('id' => '98','country_name' => 'Hungary','nationality' => 'Hungarian','dial_code' => '+36','iso_alpha_2' => 'HU','iso_alpha_3' => 'HUN'),
  array('id' => '99','country_name' => 'Iceland','nationality' => 'Icelander','dial_code' => '+354','iso_alpha_2' => 'IS','iso_alpha_3' => 'ISL'),
  array('id' => '100','country_name' => 'India','nationality' => 'Indian','dial_code' => '+91','iso_alpha_2' => 'IN','iso_alpha_3' => 'IND'),
  array('id' => '101','country_name' => 'Indonesia','nationality' => 'Indonesian','dial_code' => '+62','iso_alpha_2' => 'ID','iso_alpha_3' => 'IDN'),
  array('id' => '102','country_name' => 'Iran','nationality' => 'Iranian','dial_code' => '+98','iso_alpha_2' => 'IR','iso_alpha_3' => 'IRN'),
  array('id' => '103','country_name' => 'Iraq','nationality' => 'Iraqi','dial_code' => '+964','iso_alpha_2' => 'IQ','iso_alpha_3' => 'IRQ'),
  array('id' => '104','country_name' => 'Ireland','nationality' => 'Irish','dial_code' => '+353','iso_alpha_2' => 'IE','iso_alpha_3' => 'IRL'),
  array('id' => '105','country_name' => 'Isle Of Man','nationality' => 'Isle Of Man','dial_code' => '+44','iso_alpha_2' => 'IM','iso_alpha_3' => 'IMN'),
  array('id' => '106','country_name' => 'Israel','nationality' => 'Israeli','dial_code' => '+972','iso_alpha_2' => 'IL','iso_alpha_3' => 'ISR'),
  array('id' => '107','country_name' => 'Italy','nationality' => 'Italian','dial_code' => '+39','iso_alpha_2' => 'IT','iso_alpha_3' => 'ITA'),
  array('id' => '108','country_name' => 'Jamaica','nationality' => 'Jamaican','dial_code' => '+1','iso_alpha_2' => 'JM','iso_alpha_3' => 'JAM'),
  array('id' => '109','country_name' => 'Japan','nationality' => 'Japanese','dial_code' => '+81','iso_alpha_2' => 'JP','iso_alpha_3' => 'JPN'),
  array('id' => '110','country_name' => 'Jersey','nationality' => 'Jersey','dial_code' => '+44','iso_alpha_2' => 'JE','iso_alpha_3' => 'JEY'),
  array('id' => '111','country_name' => 'Jordan','nationality' => 'Jordanian','dial_code' => '+962','iso_alpha_2' => 'JO','iso_alpha_3' => 'JOR'),
  array('id' => '112','country_name' => 'Kazakhstan','nationality' => 'Kazakhstani','dial_code' => '+7','iso_alpha_2' => 'KZ','iso_alpha_3' => 'KAZ'),
  array('id' => '113','country_name' => 'Kenya','nationality' => 'Kenyan','dial_code' => '+254','iso_alpha_2' => 'KE','iso_alpha_3' => 'KEN'),
  array('id' => '114','country_name' => 'Kiribati','nationality' => 'Kiribatin','dial_code' => '+686','iso_alpha_2' => 'KI','iso_alpha_3' => 'KIR'),
  array('id' => '115','country_name' => 'Kosovo','nationality' => 'Kosovar','dial_code' => '+383','iso_alpha_2' => 'XK','iso_alpha_3' => 'XXK'),
  array('id' => '116','country_name' => 'Korea South','nationality' => 'Korean (South)','dial_code' => '+82','iso_alpha_2' => 'KR','iso_alpha_3' => 'KOR'),
  array('id' => '117','country_name' => 'Korea North','nationality' => 'Korean (North)','dial_code' => '+850','iso_alpha_2' => 'KP','iso_alpha_3' => 'PRK'),
  array('id' => '118','country_name' => 'Kuwait','nationality' => 'Kuwaiti','dial_code' => '+965','iso_alpha_2' => 'KW','iso_alpha_3' => 'KWT'),
  array('id' => '119','country_name' => 'Kyrgyzstan','nationality' => 'Kyrgyz','dial_code' => '+996','iso_alpha_2' => 'KG','iso_alpha_3' => 'KGZ'),
  array('id' => '120','country_name' => 'Lao People\'s Democratic Republic','nationality' => 'Laotians','dial_code' => '+856','iso_alpha_2' => 'LA','iso_alpha_3' => 'LAO'),
  array('id' => '121','country_name' => 'Latvia','nationality' => 'Latvian','dial_code' => '+371','iso_alpha_2' => 'LV','iso_alpha_3' => 'LVA'),
  array('id' => '122','country_name' => 'Lebanon','nationality' => 'Lebanese','dial_code' => '+961','iso_alpha_2' => 'LB','iso_alpha_3' => 'LBN'),
  array('id' => '123','country_name' => 'Lesotho','nationality' => 'Lesothon','dial_code' => '+266','iso_alpha_2' => 'LS','iso_alpha_3' => 'LSO'),
  array('id' => '124','country_name' => 'Liberia','nationality' => 'Liberian','dial_code' => '+231','iso_alpha_2' => 'LR','iso_alpha_3' => 'LBR'),
  array('id' => '125','country_name' => 'Libya','nationality' => 'Libyan','dial_code' => '+218','iso_alpha_2' => 'LY','iso_alpha_3' => 'LBY'),
  array('id' => '126','country_name' => 'Liechtenstein','nationality' => 'Liechtensteiner','dial_code' => '+423','iso_alpha_2' => 'LI','iso_alpha_3' => 'LIE'),
  array('id' => '127','country_name' => 'Lithuania','nationality' => 'Lithuanian','dial_code' => '+370','iso_alpha_2' => 'LT','iso_alpha_3' => 'LTU'),
  array('id' => '128','country_name' => 'Luxembourg','nationality' => 'Luxembourger','dial_code' => '+352','iso_alpha_2' => 'LU','iso_alpha_3' => 'LUX'),
  array('id' => '129','country_name' => 'Macao','nationality' => 'Macedonianv','dial_code' => '+853','iso_alpha_2' => 'MO','iso_alpha_3' => 'MAC'),
  array('id' => '130','country_name' => 'Macedonia','nationality' => 'Macedonian','dial_code' => '+389','iso_alpha_2' => 'MK','iso_alpha_3' => 'MKD'),
  array('id' => '131','country_name' => 'Madagascar','nationality' => 'Madagascarian','dial_code' => '+261','iso_alpha_2' => 'MG','iso_alpha_3' => 'MDG'),
  array('id' => '132','country_name' => 'Malawi','nationality' => 'Malawian','dial_code' => '+265','iso_alpha_2' => 'MW','iso_alpha_3' => 'MWI'),
  array('id' => '133','country_name' => 'Malaysia','nationality' => 'Malaysian','dial_code' => '+60','iso_alpha_2' => 'MY','iso_alpha_3' => 'MYS'),
  array('id' => '134','country_name' => 'Maldives','nationality' => 'Maldivan','dial_code' => '+960','iso_alpha_2' => 'MV','iso_alpha_3' => 'MDV'),
  array('id' => '135','country_name' => 'Mali','nationality' => 'Malian','dial_code' => '+223','iso_alpha_2' => 'ML','iso_alpha_3' => 'MLI'),
  array('id' => '136','country_name' => 'Malta','nationality' => 'Maltese','dial_code' => '+356','iso_alpha_2' => 'MT','iso_alpha_3' => 'MLT'),
  array('id' => '137','country_name' => 'Marshall Islands','nationality' => 'Marshallese','dial_code' => '+692','iso_alpha_2' => 'MH','iso_alpha_3' => 'MHL'),
  array('id' => '138','country_name' => 'Martinique','nationality' => 'Martinicans','dial_code' => '+596','iso_alpha_2' => 'MQ','iso_alpha_3' => 'MTG'),
  array('id' => '139','country_name' => 'Mauritania','nationality' => 'Mauritian','dial_code' => '+222','iso_alpha_2' => 'MR','iso_alpha_3' => 'MRT'),
  array('id' => '140','country_name' => 'Mauritius','nationality' => 'Mauritiusian','dial_code' => '+230','iso_alpha_2' => 'MU','iso_alpha_3' => 'MUS'),
  array('id' => '141','country_name' => 'Mayotte','nationality' => 'Mayottes','dial_code' => '+262','iso_alpha_2' => 'YT','iso_alpha_3' => 'MYT'),
  array('id' => '142','country_name' => 'Mexico','nationality' => 'Mexican','dial_code' => '+52','iso_alpha_2' => 'MX','iso_alpha_3' => 'MEX'),
  array('id' => '143','country_name' => 'Micronesia','nationality' => 'Micronesians','dial_code' => '+691','iso_alpha_2' => 'FM','iso_alpha_3' => 'FSM'),
  array('id' => '144','country_name' => 'Moldova','nationality' => 'Moldovan','dial_code' => '+373','iso_alpha_2' => 'MD','iso_alpha_3' => 'MDA'),
  array('id' => '145','country_name' => 'Monaco','nationality' => 'Monacan','dial_code' => '+377','iso_alpha_2' => 'MC','iso_alpha_3' => 'MCO'),
  array('id' => '146','country_name' => 'Mongolia','nationality' => 'Mongolian','dial_code' => '+976','iso_alpha_2' => 'MN','iso_alpha_3' => 'MNG'),
  array('id' => '147','country_name' => 'Montenegro','nationality' => 'Montenegrin','dial_code' => '+382','iso_alpha_2' => 'ME','iso_alpha_3' => 'MNE'),
  array('id' => '148','country_name' => 'Montserrat','nationality' => 'Montserratan','dial_code' => '+1','iso_alpha_2' => 'MS','iso_alpha_3' => 'MSR'),
  array('id' => '149','country_name' => 'Morocco','nationality' => 'Moroccan','dial_code' => '+212','iso_alpha_2' => 'MA','iso_alpha_3' => 'MAR'),
  array('id' => '150','country_name' => 'Mozambique','nationality' => 'Mozambican','dial_code' => '+258','iso_alpha_2' => 'MZ','iso_alpha_3' => 'MOZ'),
  array('id' => '151','country_name' => 'Myanmar','nationality' => 'Myanmarian','dial_code' => '+95','iso_alpha_2' => 'MM','iso_alpha_3' => 'MMR'),
  array('id' => '152','country_name' => 'Namibia','nationality' => 'Namibian','dial_code' => '+264','iso_alpha_2' => 'NA','iso_alpha_3' => 'NAM'),
  array('id' => '153','country_name' => 'Nauru','nationality' => 'Nauruan','dial_code' => '+264','iso_alpha_2' => 'NR','iso_alpha_3' => 'NRU'),
  array('id' => '154','country_name' => 'Nepal','nationality' => 'Nepalese','dial_code' => '+977','iso_alpha_2' => 'NP','iso_alpha_3' => 'NPL'),
  array('id' => '155','country_name' => 'Netherlands','nationality' => 'Dutch','dial_code' => '+31','iso_alpha_2' => 'NL','iso_alpha_3' => 'NDL'),
  array('id' => '156','country_name' => 'Netherlands Antilles','nationality' => 'Netherlands Antilles','dial_code' => '+599','iso_alpha_2' => 'AN','iso_alpha_3' => 'ANT'),
  array('id' => '157','country_name' => 'New Caledonia','nationality' => 'Caledonian','dial_code' => '+687','iso_alpha_2' => 'NC','iso_alpha_3' => 'NCL'),
  array('id' => '158','country_name' => 'New Zealand','nationality' => 'New Zealander','dial_code' => '+64','iso_alpha_2' => 'NZ','iso_alpha_3' => 'NZL'),
  array('id' => '159','country_name' => 'Nicaragua','nationality' => 'Nicaraguan','dial_code' => '+505','iso_alpha_2' => 'NI','iso_alpha_3' => 'NIC'),
  array('id' => '160','country_name' => 'Niger','nationality' => 'Nigerien','dial_code' => '+227','iso_alpha_2' => 'NE','iso_alpha_3' => 'NER'),
  array('id' => '161','country_name' => 'Nigeria','nationality' => 'Nigerian','dial_code' => '+234','iso_alpha_2' => 'NG','iso_alpha_3' => 'NGA'),
  array('id' => '162','country_name' => 'Niue','nationality' => 'Niue','dial_code' => '+683','iso_alpha_2' => 'NU','iso_alpha_3' => 'NIU'),
  array('id' => '163','country_name' => 'Norfolk Island','nationality' => 'Norfolk Islander','dial_code' => '+672','iso_alpha_2' => 'NF','iso_alpha_3' => 'NFK'),
  array('id' => '164','country_name' => 'Northern Mariana Islands','nationality' => 'Northern Mariana Islander','dial_code' => '+1','iso_alpha_2' => 'MP','iso_alpha_3' => 'MNP'),
  array('id' => '165','country_name' => 'Norway','nationality' => 'Norwegian','dial_code' => '+47','iso_alpha_2' => 'NO','iso_alpha_3' => 'NOR'),
  array('id' => '166','country_name' => 'Oman','nationality' => 'Omani','dial_code' => '+968','iso_alpha_2' => 'OM','iso_alpha_3' => 'OMN'),
  array('id' => '167','country_name' => 'Pakistan','nationality' => 'Pakistani','dial_code' => '+92','iso_alpha_2' => 'PK','iso_alpha_3' => 'PAK'),
  array('id' => '168','country_name' => 'Palau','nationality' => 'Palauan','dial_code' => '+680','iso_alpha_2' => 'PW','iso_alpha_3' => 'PLW'),
  array('id' => '169','country_name' => 'Palestine','nationality' => 'Palestinian','dial_code' => '+970','iso_alpha_2' => 'PS','iso_alpha_3' => 'PSE'),
  array('id' => '170','country_name' => 'Panama','nationality' => 'Panamanian','dial_code' => '+507','iso_alpha_2' => 'PA','iso_alpha_3' => 'PAN'),
  array('id' => '171','country_name' => 'Papua New Guinea','nationality' => 'Papua New Guinean','dial_code' => '+675','iso_alpha_2' => 'PG','iso_alpha_3' => 'PNG'),
  array('id' => '172','country_name' => 'Paraguay','nationality' => 'Paraguayan','dial_code' => '+595','iso_alpha_2' => 'PY','iso_alpha_3' => 'PRY'),
  array('id' => '173','country_name' => 'Peru','nationality' => 'Peruvian','dial_code' => '+51','iso_alpha_2' => 'PE','iso_alpha_3' => 'PER'),
  array('id' => '174','country_name' => 'Philippines','nationality' => 'Philippine','dial_code' => '+63','iso_alpha_2' => 'PH','iso_alpha_3' => 'PHL'),
  array('id' => '175','country_name' => 'Pitcairn','nationality' => 'Pitcairn','dial_code' => '+64','iso_alpha_2' => 'PN','iso_alpha_3' => 'PCN'),
  array('id' => '176','country_name' => 'Poland','nationality' => 'Polish','dial_code' => '+48','iso_alpha_2' => 'PL','iso_alpha_3' => 'POL'),
  array('id' => '177','country_name' => 'Portugal','nationality' => 'Portuguese','dial_code' => '+351','iso_alpha_2' => 'PT','iso_alpha_3' => 'PRT'),
  array('id' => '178','country_name' => 'Puerto Rico','nationality' => 'Puerto Rican','dial_code' => '+1','iso_alpha_2' => 'PR','iso_alpha_3' => 'PRI'),
  array('id' => '179','country_name' => 'Qatar','nationality' => 'Qatari','dial_code' => '+974','iso_alpha_2' => 'QA','iso_alpha_3' => 'QAT'),
  array('id' => '180','country_name' => 'Reunion','nationality' => 'Reunion','dial_code' => '+262','iso_alpha_2' => 'RE','iso_alpha_3' => 'REU'),
  array('id' => '181','country_name' => 'Romania','nationality' => 'Romanian','dial_code' => '+40','iso_alpha_2' => 'RO','iso_alpha_3' => 'ROU'),
  array('id' => '182','country_name' => 'Russian Federation','nationality' => 'Russian','dial_code' => '+7','iso_alpha_2' => 'RU','iso_alpha_3' => 'RUS'),
  array('id' => '183','country_name' => 'Rwanda','nationality' => 'Rwandan','dial_code' => '+250','iso_alpha_2' => 'RW','iso_alpha_3' => 'RWA'),
  array('id' => '184','country_name' => 'Saint Barthelemy','nationality' => 'Saint Barthélemois','dial_code' => '+590','iso_alpha_2' => 'BL','iso_alpha_3' => 'BLM'),
  array('id' => '185','country_name' => 'Saint Helena','nationality' => 'Saint Helenians','dial_code' => '+290','iso_alpha_2' => 'SH','iso_alpha_3' => 'SHN'),
  array('id' => '186','country_name' => 'Saint Kitts And Nevis','nationality' => 'Kittitian/Nevisian','dial_code' => '+1','iso_alpha_2' => 'KN','iso_alpha_3' => 'KNA'),
  array('id' => '187','country_name' => 'Saint Lucia','nationality' => 'Saint Lucian','dial_code' => '+1','iso_alpha_2' => 'LC','iso_alpha_3' => 'LCA'),
  array('id' => '188','country_name' => 'Saint Martin','nationality' => 'Saint Martiner','dial_code' => '+590','iso_alpha_2' => 'MF','iso_alpha_3' => 'MAF'),
  array('id' => '189','country_name' => 'Saint Pierre And Miquelon','nationality' => 'Saint-Pierrais/Miquelonnais','dial_code' => '+508','iso_alpha_2' => 'PM','iso_alpha_3' => 'PSM'),
  array('id' => '190','country_name' => 'Saint Vincent And Grenadines','nationality' => 'Vincentians','dial_code' => '+1','iso_alpha_2' => 'VC','iso_alpha_3' => 'VCT'),
  array('id' => '191','country_name' => 'Samoa','nationality' => 'Samoan','dial_code' => '+685','iso_alpha_2' => 'WS','iso_alpha_3' => 'WSM'),
  array('id' => '192','country_name' => 'San Marino','nationality' => 'San Marinese','dial_code' => '+378','iso_alpha_2' => 'SM','iso_alpha_3' => 'SMR'),
  array('id' => '193','country_name' => 'Sao Tome And Principe','nationality' => 'Sao Tomean','dial_code' => '+239','iso_alpha_2' => 'ST','iso_alpha_3' => 'STP'),
  array('id' => '194','country_name' => 'Saudi Arabia','nationality' => 'Saudi','dial_code' => '+996','iso_alpha_2' => 'SA','iso_alpha_3' => 'SAU'),
  array('id' => '195','country_name' => 'Senegal','nationality' => 'Senegalese','dial_code' => '+221','iso_alpha_2' => 'SN','iso_alpha_3' => 'SEN'),
  array('id' => '196','country_name' => 'Serbia','nationality' => 'Serbian','dial_code' => '+381','iso_alpha_2' => 'RS','iso_alpha_3' => 'SRB'),
  array('id' => '197','country_name' => 'Seychelles','nationality' => 'Seychellois','dial_code' => '+248','iso_alpha_2' => 'SC','iso_alpha_3' => 'SYC'),
  array('id' => '198','country_name' => 'Sierra Leone','nationality' => 'Sierra Leonean','dial_code' => '+232','iso_alpha_2' => 'SL','iso_alpha_3' => 'SLE'),
  array('id' => '199','country_name' => 'Sint Maarten','nationality' => 'Sint Maartener','dial_code' => '+1','iso_alpha_2' => 'SX','iso_alpha_3' => 'SXM'),
  array('id' => '200','country_name' => 'Slovakia','nationality' => 'Slovakian','dial_code' => '+421','iso_alpha_2' => 'SK','iso_alpha_3' => 'SVK'),
  array('id' => '201','country_name' => 'Slovenia','nationality' => 'Slovenian','dial_code' => '+386','iso_alpha_2' => 'SI','iso_alpha_3' => 'SVN'),
  array('id' => '202','country_name' => 'Solomon Islands','nationality' => 'Solomon Islander','dial_code' => '+677','iso_alpha_2' => 'SB','iso_alpha_3' => 'SLB'),
  array('id' => '203','country_name' => 'Somalia','nationality' => 'Somali','dial_code' => '+252','iso_alpha_2' => 'SO','iso_alpha_3' => 'SOM'),
  array('id' => '204','country_name' => 'South Africa','nationality' => 'South African','dial_code' => '+27','iso_alpha_2' => 'ZA','iso_alpha_3' => 'ZAF'),
  array('id' => '205','country_name' => 'South Sudan','nationality' => 'South Sudanese','dial_code' => '+211','iso_alpha_2' => 'SS','iso_alpha_3' => 'SSD'),
  array('id' => '206','country_name' => 'Spain','nationality' => 'Spanish','dial_code' => '+34','iso_alpha_2' => 'ES','iso_alpha_3' => 'ESP'),
  array('id' => '207','country_name' => 'Sri Lanka','nationality' => 'Sri Lankan','dial_code' => '+94','iso_alpha_2' => 'LK','iso_alpha_3' => 'LKA'),
  array('id' => '208','country_name' => 'Sudan','nationality' => 'Sudanese','dial_code' => '+249','iso_alpha_2' => 'SD','iso_alpha_3' => 'SDN'),
  array('id' => '209','country_name' => 'Suriname','nationality' => 'Surinamese','dial_code' => '+597','iso_alpha_2' => 'SR','iso_alpha_3' => 'SUR'),
  array('id' => '210','country_name' => 'Svalbard And Jan Mayen','nationality' => 'Svalbard And Jan Mayen','dial_code' => '+47','iso_alpha_2' => 'SJ','iso_alpha_3' => 'SJM'),
  array('id' => '211','country_name' => 'Swaziland','nationality' => 'Swazi','dial_code' => '+268','iso_alpha_2' => 'SZ','iso_alpha_3' => 'SWZ'),
  array('id' => '212','country_name' => 'Sweden','nationality' => 'Swedish','dial_code' => '+46','iso_alpha_2' => 'SE','iso_alpha_3' => 'SWE'),
  array('id' => '213','country_name' => 'Switzerland','nationality' => 'Swiss','dial_code' => '+41','iso_alpha_2' => 'CH','iso_alpha_3' => 'CHE'),
  array('id' => '214','country_name' => 'Syria','nationality' => 'Syrian','dial_code' => '+963','iso_alpha_2' => 'SY','iso_alpha_3' => 'SYR'),
  array('id' => '215','country_name' => 'Taiwan','nationality' => 'Taiwanese','dial_code' => '+886','iso_alpha_2' => 'TW','iso_alpha_3' => 'TWN'),
  array('id' => '216','country_name' => 'Tajikistan','nationality' => 'Tajik','dial_code' => '+992','iso_alpha_2' => 'TJ','iso_alpha_3' => 'TJK'),
  array('id' => '217','country_name' => 'Tanzania','nationality' => 'Tanzanian','dial_code' => '+255','iso_alpha_2' => 'TZ','iso_alpha_3' => 'TZA'),
  array('id' => '218','country_name' => 'Thailand','nationality' => 'Thai','dial_code' => '+66','iso_alpha_2' => 'TH','iso_alpha_3' => 'THA'),
  array('id' => '219','country_name' => 'Timor-Leste','nationality' => 'Timorese','dial_code' => '+670','iso_alpha_2' => 'TL','iso_alpha_3' => 'TLS'),
  array('id' => '220','country_name' => 'Togo','nationality' => 'Togolese','dial_code' => '+228','iso_alpha_2' => 'TG','iso_alpha_3' => 'TGO'),
  array('id' => '221','country_name' => 'Tokelau','nationality' => 'Tokelau','dial_code' => '+690','iso_alpha_2' => 'TK','iso_alpha_3' => 'TKL'),
  array('id' => '222','country_name' => 'Tonga','nationality' => 'Tongan','dial_code' => '+676','iso_alpha_2' => 'TO','iso_alpha_3' => 'TON'),
  array('id' => '223','country_name' => 'Trinidad And Tobago','nationality' => 'Trinidadian/Tobagonian','dial_code' => '+1','iso_alpha_2' => 'TT','iso_alpha_3' => 'TTO'),
  array('id' => '224','country_name' => 'Tunisia','nationality' => 'Tunisian','dial_code' => '+216','iso_alpha_2' => 'TN','iso_alpha_3' => 'TUN'),
  array('id' => '225','country_name' => 'Turkey','nationality' => 'Turkish','dial_code' => '+90','iso_alpha_2' => 'TR','iso_alpha_3' => 'TUR'),
  array('id' => '226','country_name' => 'Turkmenistan','nationality' => 'Turkmen','dial_code' => '+993','iso_alpha_2' => 'TM','iso_alpha_3' => 'TKM'),
  array('id' => '227','country_name' => 'Turks And Caicos Islands','nationality' => 'Turks And Caicos Islander','dial_code' => '+1','iso_alpha_2' => 'TC','iso_alpha_3' => 'TCA'),
  array('id' => '228','country_name' => 'Tuvalu','nationality' => 'Tuvaluan','dial_code' => '+688','iso_alpha_2' => 'TV','iso_alpha_3' => 'TUV'),
  array('id' => '229','country_name' => 'Uganda','nationality' => 'Ugandan','dial_code' => '+256','iso_alpha_2' => 'UG','iso_alpha_3' => 'UGA'),
  array('id' => '230','country_name' => 'Ukraine','nationality' => 'Ukrainian','dial_code' => '+380','iso_alpha_2' => 'UA','iso_alpha_3' => 'UKR'),
  array('id' => '231','country_name' => 'United Arab Emirates','nationality' => 'Emirati','dial_code' => '+971','iso_alpha_2' => 'AE','iso_alpha_3' => 'ARE'),
  array('id' => '232','country_name' => 'United Kingdom','nationality' => 'British','dial_code' => '+44','iso_alpha_2' => 'GB','iso_alpha_3' => 'GBR'),
  array('id' => '233','country_name' => 'United States','nationality' => 'American','dial_code' => '+1','iso_alpha_2' => 'US','iso_alpha_3' => 'USA'),
  array('id' => '234','country_name' => 'Uruguay','nationality' => 'Uruguayan','dial_code' => '+598','iso_alpha_2' => 'UY','iso_alpha_3' => 'URY'),
  array('id' => '235','country_name' => 'Uzbekistan','nationality' => 'Uzbekistani','dial_code' => '+998','iso_alpha_2' => 'UZ','iso_alpha_3' => 'UZB'),
  array('id' => '236','country_name' => 'Vanuatu','nationality' => 'Vanuatu','dial_code' => '+678','iso_alpha_2' => 'VU','iso_alpha_3' => 'VUT'),
  array('id' => '237','country_name' => 'Vatican City (Holy See)','nationality' => 'Vatican Citizen','dial_code' => '+379','iso_alpha_2' => 'VA','iso_alpha_3' => 'VAT'),
  array('id' => '238','country_name' => 'Venezuela','nationality' => 'Venezuelan','dial_code' => '+58','iso_alpha_2' => 'VE','iso_alpha_3' => 'VEN'),
  array('id' => '239','country_name' => 'Vietnam','nationality' => 'Vietnamese','dial_code' => '+84','iso_alpha_2' => 'VN','iso_alpha_3' => 'VNM'),
  array('id' => '240','country_name' => 'Virgin Islands, U.S.','nationality' => 'U.S Virgin Islander','dial_code' => '+1','iso_alpha_2' => 'VI','iso_alpha_3' => 'VIR'),
  array('id' => '241','country_name' => 'Wallis And Futuna','nationality' => 'Welsh','dial_code' => '+681','iso_alpha_2' => 'WF','iso_alpha_3' => 'WLF'),
  array('id' => '242','country_name' => 'Western Sahara','nationality' => 'Western Saharan','dial_code' => '+212','iso_alpha_2' => 'EH','iso_alpha_3' => 'ESH'),
  array('id' => '243','country_name' => 'Yemen','nationality' => 'Yemenite','dial_code' => '+967','iso_alpha_2' => 'YE','iso_alpha_3' => 'YEM'),
  array('id' => '244','country_name' => 'Zambia','nationality' => 'Zambian','dial_code' => '+260','iso_alpha_2' => 'ZM','iso_alpha_3' => 'ZMB'),
  array('id' => '245','country_name' => 'Zimbabwe','nationality' => 'Zimbabwean','dial_code' => '+263','iso_alpha_2' => 'ZW','iso_alpha_3' => 'ZWE')
);
